name: Build and release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare cloudimg 
        run: ./prep-images.sh 
      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest 
          release_name: Latest
          body: |
            Ubuntu cloudimg for Proxmox
          draft: false
          prerelease: false
      
      - name: Upload release asset
        uses: csexton/release-asset-action@v2
        with:
          pattern: "out/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
